revision: v1
type: plugin
name: NativeDimensions
versions:
  - version: 1.0.0-beta4
    from: poggit_pmmp
  - version: 1.0.0-beta3
    from: poggit_pmmp
  - version: 1.0.0-beta2
    from: poggit_pmmp
  - version: 1.0.0-beta1
    from: poggit_pmmp
