revision: v1
type: plugin
name: Parties
versions:
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.2.2
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.3
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
