revision: v1
type: plugin
name: AntiInstaBreak
versions:
  - version: 1.0.0
    from: poggit_pmmp
  - version: 0.1.2
    from: poggit_pmmp
  - version: 0.1.1
    from: poggit_pmmp
  - version: 0.1.0
    from: poggit_pmmp
