revision: v1
type: plugin
name: Football
versions:
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.3.5
    from: poggit_pmmp
  - version: 1.3.4
    from: poggit_pmmp
  - version: 1.3.3
    from: poggit_pmmp
  - version: 1.3.2
    from: poggit_pmmp
  - version: 1.3.1
    from: poggit_pmmp
  - version: 1.3.0
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
