revision: v1
type: plugin
name: BlockReplacer
versions:
  - version: 1.3.0
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.0
    from: poggit_pmmp
