revision: v1
type: plugin
name: Hotbar
versions:
  - version: 2.0.6
    from: poggit_pmmp
  - version: 2.0.4
    from: poggit_pmmp
  - version: 2.0.3
    from: poggit_pmmp
  - version: 2.0.2
    from: poggit_pmmp
  - version: 2.0.1
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: 1.1.6
    from: poggit_pmmp
  - version: 1.1.5
    from: poggit_pmmp
  - version: 1.1.4
    from: poggit_pmmp
