revision: v1
type: plugin
name: StackStorage
versions:
  - version: 1.2.1
    from: poggit_pmmp
  - version: 1.2.0
    from: poggit_pmmp
  - version: 1.1.4
    from: poggit_pmmp
  - version: 1.1.3
    from: poggit_pmmp
  - version: 1.1.2
    from: poggit_pmmp
  - version: 1.1.1
    from: poggit_pmmp
  - version: 1.1.0
    from: poggit_pmmp
  - version: 1.0.2
    from: poggit_pmmp
  - version: 1.0.1
    from: poggit_pmmp
  - version: 0.0.7
    from: poggit_pmmp
  - version: 0.0.5
    from: poggit_pmmp
