revision: v1
type: plugin
name: AdvanceDeaths
versions:
  - version: '3.4'
    from: poggit_pmmp
  - version: '3.0'
    from: poggit_pmmp
  - version: 2.7.1
    from: poggit_pmmp
  - version: '2.7'
    from: poggit_pmmp
  - version: '2.6'
    from: poggit_pmmp
  - version: '2.5'
    from: poggit_pmmp
  - version: 2.0.0
    from: poggit_pmmp
  - version: '1.8'
    from: poggit_pmmp
  - version: '1.6'
    from: poggit_pmmp
  - version: '1.5'
    from: poggit_pmmp
  - version: '1.4'
    from: poggit_pmmp
  - version: '1.0'
    from: poggit_pmmp
