name: Find Versions to Pocketmine
on:
  schedule:
    - cron: 0 */2 * * *
  push:
    branches:
      - main
jobs:
  pocketmine:
    name: Find Version to Pocketmine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v2.5.1
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "16.x"
      - run: npm ci
      - run: npm run pocketmine:find
      - run: |
          git pull --rebase || git pull
          (git add . && git commit -m "Update Pocketmine Packages" && git push) || echo "no Commit Files."
